import numpy as np


def export_to_typst(data, filepath):
    """
    Export a dictionary of values to a Typst file as constants.
    """
    with open(filepath, "w") as f:
        f.write("// Generated by Python scripts\n")
        for key, value in data.items():
            if isinstance(value, (int, float, np.float64, np.int64)):
                f.write(f"#let {key} = {value}\n")
            elif isinstance(value, str):
                f.write(f'#let {key} = "{value}"\n')
            else:
                f.write(f"#let {key} = {repr(value)}\n")
    print(f"Exported metrics to {filepath}")
